In [2]:
# import numpy
import numpy as np 

In [11]:
# Numpy program to create a square matrix
# Dimensions as entered by user
user_dim = input(f"Specify dimensions of matrix, separated by a space:   ")
dim = tuple(int(item)for item in user_dim.split())

# Create matrix
user_dim_matrix = np.ones((dim))
user_dim_matrix = np.zeros((dim), dtype=int)

# Fill matrix with checkerboard pattern
user_dim_matrix[1::2,::2] = 1
user_dim_matrix[::2, 1::2] = 1



Specify dimensions of matrix, separated by a space:   7 7


In [7]:
print(user_dim_matrix)

[[0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]]


In [12]:
# Numpy program to create a 2D array
# With character X on the border
# And character O inside the array

_2d_array = np.array([["X","X","X","X"], ["X","X","X","X"], ["X","X","X","X"], ["X","X","X","X"]])
_2d_array[1:-1, 1:-1] = "O"

In [23]:
print(_2d_array)

[['X' 'X' 'X' 'X']
 ['X' 'O' 'O' 'X']
 ['X' 'O' 'O' 'X']
 ['X' 'X' 'X' 'X']]


In [32]:
# Numpy program to extract all contiguous 3x3 blocks from any 12x12 matrix
# Create original array
orig_arr = np.random.randint(0,4,(12,12))

n = 3
i = 1 + (orig_arr.shape[0]-3)
j = 1 + (orig_arr.shape[1]-3)
outcome = np.lib.stride_tricks.as_strided(orig_arr, shape=(i,j,n,n), strides= orig_arr.strides + orig_arr.strides)


In [27]:
print(f"Original array:\n", orig_arr)

Original array:
 [[2 3 4 1 0 1 3 1 1 2 4 4]
 [2 4 2 2 0 3 0 0 4 1 0 4]
 [0 3 1 2 2 2 2 2 2 0 3 1]
 [0 3 4 3 3 1 2 2 4 3 0 1]
 [1 3 1 0 1 1 2 4 3 0 1 3]
 [4 2 2 0 4 3 2 1 2 4 4 3]
 [4 2 1 0 3 1 0 1 3 0 0 1]
 [0 4 0 0 2 0 2 3 2 1 4 3]
 [3 4 2 2 4 0 0 2 1 0 1 4]
 [2 1 2 2 2 1 1 3 4 0 2 0]
 [0 1 0 3 4 3 3 0 0 1 1 3]
 [0 4 1 4 4 3 3 2 1 4 2 4]]


In [33]:
print("\nContiguous 3x3 blocks:\n")
print("\n", outcome)


Contiguous 3x3 blocks:


 [[[[1 1 1]
   [2 2 3]
   [2 2 1]]

  [[1 1 3]
   [2 3 3]
   [2 1 2]]

  [[1 3 0]
   [3 3 1]
   [1 2 3]]

  [[3 0 0]
   [3 1 2]
   [2 3 0]]

  [[0 0 0]
   [1 2 3]
   [3 0 2]]

  [[0 0 2]
   [2 3 3]
   [0 2 0]]

  [[0 2 2]
   [3 3 0]
   [2 0 2]]

  [[2 2 3]
   [3 0 2]
   [0 2 3]]

  [[2 3 3]
   [0 2 0]
   [2 3 1]]

  [[3 3 2]
   [2 0 1]
   [3 1 1]]]


 [[[2 2 3]
   [2 2 1]
   [1 3 3]]

  [[2 3 3]
   [2 1 2]
   [3 3 2]]

  [[3 3 1]
   [1 2 3]
   [3 2 2]]

  [[3 1 2]
   [2 3 0]
   [2 2 0]]

  [[1 2 3]
   [3 0 2]
   [2 0 2]]

  [[2 3 3]
   [0 2 0]
   [0 2 0]]

  [[3 3 0]
   [2 0 2]
   [2 0 3]]

  [[3 0 2]
   [0 2 3]
   [0 3 3]]

  [[0 2 0]
   [2 3 1]
   [3 3 3]]

  [[2 0 1]
   [3 1 1]
   [3 3 0]]]


 [[[2 2 1]
   [1 3 3]
   [0 1 3]]

  [[2 1 2]
   [3 3 2]
   [1 3 0]]

  [[1 2 3]
   [3 2 2]
   [3 0 2]]

  [[2 3 0]
   [2 2 0]
   [0 2 2]]

  [[3 0 2]
   [2 0 2]
   [2 2 1]]

  [[0 2 0]
   [0 2 0]
   [2 1 2]]

  [[2 0 2]
   [2 0 3]
   [1 2 2]]

  [[0 2 3]
   [0 3 3]
  